### ISSUE TITLE
[Bug]:  Cannot Find Module

### ISSUE THREAD

**Issue by zainen** [LedgerHQ/ledger-live#1378] opened 2022-09-26 17:49 UTC
### Impacted Library name

@ledgerhq/hw-transport-node-hid / -noevents

### Impacted Library version

6.20 +

### Describe the bug

```
Cannot find module '@ledgerhq/devices/hid-framing' from 'node_modules/@ledgerhq/hw-transport-node-hid-noevents/lib/TransportNodeHid.js'
```
have tests set up to connect to a ledger device and receive the pkh or pk for Tezos blockchain addresses

<img width="999" alt="image" src="https://user-images.githubusercontent.com/72581075/192345306-8842a5cd-a936-4c7f-bbc2-d121c4baf6ca.png">

### Expected behavior

Ledger should be connectable with out the missing module or error. 

happened when trying to add ability for bip32 addresses to be used with ledger. was working until the packages were updated and now nothing seems to resolve the conflict

tried on multiple types of OS

### Additional context

After an update to the packages multiple versions have stopped working because of this missing packaged

have tried:
clean builds
reinstalls
downgrades
upgrades
installing @ledgerhq/devices

**Comment by zainen** [comment] 2022-09-26 22:27
additional information 

additional information the error is coming from
line 62  in `TransforNodeHid.js` in `@ledgerhq/hw-transport-node-hid-noevents`
`var hid_framing_1 = __importDefault(require("@Ledgerhq/devices/hid-framing")); `

**Comment by zainen** [comment] 2022-09-27 01:46
after digging i found that `@ledger/devices/lib/hid-framing` works 

what im currently not figuring out is why downgrading does not resolve this issue either

**Comment by elbywan** [comment] 2022-09-27 12:50
Hi @zainen, this issues seems to be a duplicate of #763.

`@ledgerhq/devices` now uses [subpath exports](https://nodejs.org/api/packages.html#subpath-exports). I don't know why `jest-resolver` is unable to map the path, maybe you should upgrade to the latest version of `jest` or configure it manually.

Please read [this comment](https://github.com/LedgerHQ/ledger-live/issues/763#issuecomment-1209204659) for more information.

**Closed by elbywan** 2022-09-27 12:50 UTC
Labels: bug, libraries, triage
