### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by agbanusi** [LedgerHQ/ledger-live#842] opened 2022-08-04 14:01 UTC
**Details**
- Impacted Library:`@ledgerhq/hw-transport-webhid`
- Version: 6.27.1

**Describe the bug**

This is what I found 
```
./node_modules/@ledgerhq/hw-transport-webhid/lib-es/TransportWebHID.js
Module not found: Can't resolve '@ledgerhq/devices/hid-framing' in '/Users/john/Documents/apps/work/gfx-web-app/node_modules/@ledgerhq/hw-transport-webhid/lib-es'
```

**Expected behavior**

_A clear and concise description of what you expected to happen._

**Additional context**

_Add any other context about the problem here._
It seems it needs to be `import hidFraming from "@ledgerhq/devices/lib/hid-framing"` or similar instead of `import hidFraming from "@ledgerhq/devices/hid-framing";` as it seems the hid_framing is added into the lib and lib-es folder

**Comment by gre** [comment] 2022-08-04 15:22
Duplicate of https://github.com/LedgerHQ/ledger-live/issues/763

**Closed by gre** 2022-08-04 15:22 UTC
Labels: bug, libraries
