### ISSUE TITLE
Can't find @ledgerhq/devices/hid-framing 

### ISSUE THREAD

**Issue by oleg-savenok** [LedgerHQ/ledger-live#799] opened 2022-08-01 14:39 UTC
https://github.com/LedgerHQ/ledger-live/blob/ae290e27c6bcc0fc224762836eb49bfb7f3aed18/libs/ledgerjs/packages/hw-transport-webhid/src/TransportWebHID.ts#L7

Can be fixed with replacing `import hidFraming from "@ledgerhq/devices/hid-framing";` with `import hidFraming from "@ledgerhq/devices/lib/hid-framing";`

**Comment by elbywan** [comment] 2022-08-01 18:22
Duplicate of #763

**Closed by elbywan** 2022-08-01 18:22 UTC
